### ISSUE TITLE
DNU en 7 Recuerdos - Pide implementar un método pero testea otro

### ISSUE THREAD

**Issue by LeaTex** [wollok/mumuki-guia-wollok-introduccion-a-objetos#1]
En el ejercicio 7 tanto el [enunciado](https://github.com/wollok/mumuki-guia-wollok-introduccion-a-objetos/blob/master/00007_Recuerdos/description.md) como la [pista](https://github.com/wollok/mumuki-guia-wollok-introduccion-a-objetos/blob/master/00007_Recuerdos/hint.md) indican implementar el método `pasoElTiempo()`.

Pero el [test](https://github.com/wollok/mumuki-guia-wollok-introduccion-a-objetos/blob/master/00007_Recuerdos/test.) busca ejecutar un método `blancanievesCrecio()`.

Al ejecutar la solución en Mumuki arroja un error:
`espejoMagico[masBella=reina malvada] does not understand blancanievesCrecio()`

Que se puede salvar definiendo el mensaje, obviamente.

Habría que cambiar el test (o el enunciado).

**Comment by lspigariol** [comment]
corregido
