### ISSUE TITLE
8 Pasando valores - Hay una llave en lugar de paréntesis en los tests

### ISSUE THREAD

**Issue by LeaTex** [wollok/mumuki-guia-wollok-introduccion-a-objetos#2]
En Mumuki aparece el siguiente error al ejecutar la solución:

```
ERROR: missing ')' at '}'
ERROR: extraneous input '}' expecting EOF
```

El archivo de [test](https://github.com/wollok/mumuki-guia-wollok-introduccion-a-objetos/blob/master/00008_Pasando%20valores/test.) tiene una `}` en lugar de `)` (línea 5).

**Comment by lspigariol** [comment]
corregido

**Comment by LeaTex** [comment]
Gracias!
¿Cuándo estarán disponibles los fixes en Mumuki para completar la guía?

**Comment by lspigariol** [comment]
ya quedó arreglado. no lo podes ver?

**Comment by LeaTex** [comment]
Sí, ya está, no había entrado a Mumuki, pensé que no hacían el deploy directo.
Gracias!

PD: hay otro error en el ejercicio 1 de la unidad 6 sobre Colecciones, pero no encuentro el proyecto para registrar el issue. ¿en dónde lo cargo?

**Comment by lspigariol** [comment]
listo, ya lo arregle.
esas guias estan en otra organizacion, falta terminar de revisarlas y
acomodarlas.

**Comment by LeaTex** [comment]
Gracias!
